historicos: {
                fixHeaderAndSetBodyMaxHeight: 160,
                tblStyle: 'table-layout: fixed', // must
                tblClass: 'table-borderless table-sm table-responsive-sm',
                columns: [
                    { title: 'Contrato', field: 'contrato',  fixed: true },
                    { title: 'Nome', field: 'nome' },
                    { title: 'CPF/CNPJ', field: 'cpfcnpj'},
                    { title: 'Tipo de contrato', field: 'vlcontrato', sortable: true},
                    { title: 'Data do contrato', field: 'drcontrato', sortable: true},
                    { title: 'Status', field: 'status', sortable: true},
                ].map(col => (col.colStyle = { width: '200px', height: '20px' }, col)),
                data: [
                    {
                        contrato: '0001251',
                        nome: 'Nome teste',
                        cpfcnpj: '888.888.888-56',
                        vlcontrato: 'R$ 25,000.00',
                        drcontrato: '23/03/2018',
                        status: 'Ativo',
                    },
                ],
                summary: {},
                total: 0,
                query: {}
            },
            condominios: {
                fixHeaderAndSetBodyMaxHeight: 160,
                tblClass: 'table-borderless table-sm table-responsive-sm border border-top-0',
                columns: [
                    { title: 'Status', field: 'status', sortable: true},
                    { title: 'Periodo', field: 'periodo', sortable: true},
                    { title: 'Valor', field: 'valor', sortable: true},
                    { title: 'Juros', field: 'juros', sortable: true},
                    { title: 'Multa', field: 'multa', sortable: true},
                    { title: 'Correção', field: 'correcao', sortable: true},
                    { title: 'Total', field: 'total', sortable: true},
                    { title: 'Data pgto.', field: 'datapgto', sortable: true},
                    { title: 'Ações', field: 'acoes'},
                ].map(col => (col.colStyle = { width: '200px', height: '20px' }, col)),
                data: [
                    {
                        status: 'Ativo',
                        periodo: 'Periodo',
                        vencimento: '23/07/2018',
                        valor: 'R$ 51.588,00',
                        juros: '0%',
                        multa: '0%',
                        correcao: '0%',
                        total: 'R$ 57.588,00',
                        datapgto: '25/07/2018',
                        acoes: 'Action',
                    },{
                        status: 'Ativo',
                        periodo: 'Periodo',
                        vencimento: '23/07/2018',
                        valor: 'R$ 533.588,00',
                        juros: '0%',
                        multa: '0%',
                        correcao: '0%',
                        total: 'R$ 57.588,00',
                        datapgto: '25/07/2018',
                        acoes: 'Action',
                    },{
                        status: 'Ativo',
                        periodo: 'Periodo',
                        vencimento: '23/07/2018',
                        valor: 'R$ 57.588,00',
                        juros: '0%',
                        multa: '0%',
                        correcao: '0%',
                        total: 'R$ 57.588,00',
                        datapgto: '25/07/2018',
                        acoes: '',
                    },
                ],
                summary: {},
                total: 0,
                query: {}
            }